Updated Thymeleaf processors
BroadleafCommerce/Menu pull request #46
Opened 2023-04-25 13:56 UTC by MarekB01

https://github.com/BroadleafCommerce/QA/issues/4962

updated thymeleaf processors which were extended from deprecated processor

2023-04-25 14:21 UTC, troian88 reviewed
Can you attach an example of usage and how UI looks with that processors?

2023-04-25 14:55 UTC, oleksiimiroshnyk requested changes

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/AbstractMenuProcessorExtensionHandler.java
> +    public ExtensionResultStatusType addAdditionalFieldsToModel(Map<String, Object> newModelVars, String menuId, String menuName) {
this is just a stub, there is a real implementation in Theme module I don't see PR for the theme module.
I don't see why would it need menu id as current impl is interested in menuName only.

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuExpression.java
> +public interface MenuExpression extends BroadleafVariableExpression {
what is the purpose of this interface ?

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuProcessor.java
> +public class MenuProcessor implements MenuExpression {
guess we can implement BroadleafVariableExpression directly

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuProcessor.java
> +            newModelVars.put("menuName", menuService.constructMenuItemDTOsForMenu(menu));
why do we need this line ?

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuProcessor.java
> +    public Map<String, Object> getMenu(String menuId, String menuName) {
why do we need map as return type ? The idea of that method to get list of menu item dtos and put it under expected name in the map. In the new approach we don't use map we simply return what we ask for, in this case List<MenuItemDTO>

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuProcessorExtensionHandler.java
> +    public ExtensionResultStatusType addAdditionalFieldsToModel(Map<String, Object> newModelVars, String menuId, String menuName);
idea of that extension is to allow some other modules override/modify result of execution of the method.
So I think signature should be something like 
public ExtensionResultStatusType addAdditionalFieldsToModel(List<MenuItemDTO> menuItems, String menuName);

or something like that... and extension will modify menuItems as needed

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuProcessor.java
> +            newModelVars.put("menuName", menuService.constructMenuItemDTOsForMenu(menu));
guess we need something like List<MenuItemDTO>  menuItems = menuService.constructMenuItemDTOsForMenu(menu)

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuProcessor.java
> +            extensionManager.getProxy().addAdditionalFieldsToModel(newModelVars, menuId, menuName);
extensionManager.getProxy().addAdditionalFieldsToModel(menuItems, menuName);

2023-04-25 14:55 UTC, oleksiimiroshnyk commented on src/main/java/org/broadleafcommerce/menu/processor/MenuProcessor.java
>              newModelVars.put("menuLinkedData", linkedDataService.getLinkedData(menu));
just return menuItems

2023-04-26 14:44 UTC, oleksiimiroshnyk approved these changes

2023-07-06 15:04 UTC, merged